### ISSUE TITLE
超出界面范围外

### ISSUE THREAD

**Issue by SignDawn** [aesoper101/vue3-colorpicker#11]
![image](https://user-images.githubusercontent.com/48878568/145159547-7e12a2f1-584a-4ecc-b309-137df6929872.png)

默认的 css 似乎有问题，当这个内容在页面较底部时，会超出页面范围显示

**Comment by AckermanFernando** [comment]
any news about it?

**Comment by AckermanFernando** [comment]
To fix it I used window.scrollBy(0,100).  Apparently, when scrolling the page, the position of the color picker is updated.
