### ISSUE TITLE
Great Plugin, is there a way to autoclose the Colorpicker after a color is selected?

### ISSUE THREAD

**Issue by anon36** [aesoper101/vue3-colorpicker#16]

**Comment by huangcx708** [comment]
<color-picker
      v-model:pureColor="pureColor"
      :disableAlpha="true"
      @pureColorChange="pureColorChange"
      ref="colorPicker"
    />

const pureColorChange = () => {
      colorPicker.value.showPicker = false;
    };

**Comment by fabriciozeferino** [comment]
@huangcx708  Hey mate, I'm trying to use the same approach to open the modal, but it doesn't work. Is there any way around it? Thanks

**Comment by alonehover** [comment]
@fabriciozeferino pls upgrade to `2.3.0`, and try again. you can also try use `blurClose` to auto close when mouse leave popup.
