### ISSUE TITLE
[Parse Color]: Error: #000: Invalid input not EOF

### ISSUE THREAD

**Issue by DavidSprauel** [aesoper101/vue3-colorpicker#17]
I'm passing the color as HEX value in the v-model:pureColor property and i got this error.
I've search through the doc and the only example is a TS one with some code that doesn't give a hint on how it is supposed to be formatted. 

The weirdest thing is that it works, it displays the right color by default.

**Comment by the94air** [comment]
This looks like a serious problem, when you don't need to use gradients

**Comment by the94air** [comment]
Hey, @alonehover. Does this mean it's fixed? Thank you!
