### ISSUE TITLE
Cannot set properties of undefined (setting 'stringify') . GradientParser throws an error

### ISSUE THREAD

**Issue by NeroN7F** [aesoper101/vue3-colorpicker#18]
Hi. Running on Vue vite project, used to work fine with vue cli, but now GradientParser throws an error. Are there any ways to get rid of gradient library or fix an issue ? 

```
TypeError: Cannot set properties of undefined (setting 'stringify')
    at node_modules/gradient-parser/build/node.js (node.js:7:16)
    at __require (chunk-BNF35FCG.js?v=2cabb439:29:50)
    at index.es.js:33:34
```

**Comment by Linzy0526** [comment]
try to change the vite version to vite@2.6.4

> npm install vite@2.6.4
