### ISSUE TITLE
嗨，还在吗？

### ISSUE THREAD

**Issue by qcj007** [aesoper101/vue3-colorpicker#21]
作者，我看您已经好久没有更新了，我想新增RGB输入和HSB输入，请问修改完后可以重开一个npm吗？当然会注明源码来源于您

**Comment by aesoper101** [comment]
@qcj007 嗯 不好意思啊，因为工作忙又是个后端出身的也没太多的精力去维护，要更新和处理遗留下来的issues估计也是一个月后了。您可以修改再发布的没问题。
