### ISSUE TITLE
你好，渐变色默认值问题，可能是一个bug

### ISSUE THREAD

**Issue by hu5871** [aesoper101/vue3-colorpicker#22]
渐变色默认值linear-gradient(0deg, rgba(255, 255, 255, 1) 0%, rgba(0, 0, 0, 1) 100%),始终解析成为linear-gradient(0deg, rgba(255, 255, 255, 1) 0%, rgba(0, 0, 0, 1) 100%)
![image](https://user-images.githubusercontent.com/68421705/168202445-f324cf6a-c084-4e60-8fdf-a102fb88e833.png)

**Comment by hu5871** [comment]
![image](https://user-images.githubusercontent.com/68421705/168203155-e0330c4f-2209-4c6d-bed9-d02403f54dcf.png)
在demo中，尝试也是如此

**Comment by hyunchi** [comment]
怎么解决的，我也遇到了

**Comment by git-weijinhua** [comment]
![image](https://user-images.githubusercontent.com/66825542/194840829-172c8cc8-b4e7-49c8-9fd4-75bc0a12c1ac.png)
看作者的代码，这里错了

**Comment by git-weijinhua** [comment]
您好，您发送的邮件我已收到，祝您愉快！

**Comment by git-weijinhua** [comment]
您好，您发送的邮件我已收到，祝您愉快！

**Comment by alonehover** [comment]
您好：       我已收到邮件，将会尽快回复您。
