### ISSUE TITLE
Nuxt3 build issue

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [aesoper101/vue3-colorpicker#26]
Could not load raw:vue3-angle/style.css (imported by node_modules/vue3-colorpicker/index.es.js): ENOENT: no such file or directory, open 'D:\Programming\goonlinetools3\vue3-angle\style.css'

**Comment by YusufcanY** [comment]
Same on Nuxt3 stable

**Comment by Ivwc** [comment]
Same on Nuxt3 stable

**Comment by Flinty916** [comment]
Has anyone found a fix for this?

Same on Nuxt 3 RC14

**Comment by webxue** [comment]
how to solve the problem？
