### ISSUE TITLE
兄弟的你插件挂了 

### ISSUE THREAD

**Issue by hanchn** [aesoper101/vue3-colorpicker#28]
This dependency was not found:

* vue3-colorpicker in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/views/Fabric/index.vue?vue&type=script&lang=js, ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/views/NavigationDetail/components/MenuDrawer.vue?vue&type=script&lang=js and 1 other

To install it, you can run: npm install --save vue3-colorpicker

**Comment by hanchn** [comment]
依赖安装完找不到

**Comment by hanchn** [comment]
帮忙看下 解决下

**Comment by aesoper101** [comment]
@hanchn 是最新的版本么？

**Comment by Avatar4eg** [comment]
> @hanchn 是最新的版本么？

Yes. It is. 2.0.4 - ok.

**Comment by Zoomy148R** [comment]
I have same problem.

**Comment by alonehover** [comment]
@hanchn node_modules 删了重新安装也不行吗 ？
