### ISSUE TITLE
使用报错，为什么 vue3-colorPicker 下还有 node_modules ？

### ISSUE THREAD

**Issue by SignDawn** [aesoper101/vue3-colorpicker#3]
**下面的内容是部分的报错信息！**

与类型“Plugin_2”和“Plugin_2”相比，堆栈深度过高。ts(2321)
类型“import("d:/le5lecode/le5le/topology-vue/node_modules/vue3-colorpicker/node_modules/@vue/runtime-core/dist/runtime-core").Plugin”的参数不能赋给类型“import("d:/le5lecode/le5le/topology-vue/node_modules/@vue/runtime-core/dist/runtime-core").Plugin”的参数。
  不能将类型“PluginInstallFunction & { install?: PluginInstallFunction; }”分配给类型“Plugin_2”。

**Comment by aesoper101** [comment]
已在最新版本修复，

为什么会出现vue3-colorpicker/node_modules 是因为编译打包上传的时候，没有设置peerDependencies外部依赖，造成了当外部没有vue3-colorpicker所需依赖包时，它会安装到vue3-colorpicker下.
