### ISSUE TITLE
How to detect when showing event?

### ISSUE THREAD

**Issue by SuelTheDev** [aesoper101/vue3-colorpicker#32]

**Comment by khalil-alsous** [comment]
are you meaning that you want to made some functions when show the picker ?

**Comment by SuelTheDev** [comment]
> are you meaning that you want to made some functions when show the picker ?

Yes, when show and hide.

**Comment by khalil-alsous** [comment]
**I had the same problem before and there is not events like this in library, but I had do a function when show the picker like this:**

> on click on button that opening the picker, call the event and like this you can do something when show the picker

**Comment by SuelTheDev** [comment]
> 
I managed to solve it, I created the appropriate emits in the lib when the action occurs they are triggered.

**Comment by SuelTheDev** [comment]
> [SuelTheDev](https://github.com/SuelTheDev) please could you explain how to create the appropriate emissions in the library when an action occurs.

Register a new event here.

https://github.com/aesoper101/vue3-colorpicker/blob/6ba66e81fe8b408f9d34ce83a9b91aa5c1d9405f/packages/ColorPicker.vue#L92

Example: 
'onShow', 'onHide'

and call here

https://github.com/aesoper101/vue3-colorpicker/blob/6ba66e81fe8b408f9d34ce83a9b91aa5c1d9405f/packages/ColorPicker.vue#L194

`
emit('onShow')
`
