### ISSUE TITLE
选择器在浏览器底部会出现遮挡

### ISSUE THREAD

**Issue by zhuanglinxin** [aesoper101/vue3-colorpicker#34]
![image](https://user-images.githubusercontent.com/49221520/207551584-3e4e4b70-6fa5-4496-ae33-533400e838b2.png)

**Comment by zhuanglinxin** [comment]
![image](https://user-images.githubusercontent.com/49221520/210738835-bb7372d2-2810-443b-8fb9-fcf7eaa6defd.png)
更新了版本 新的问题出现了

**Comment by alonehover** [comment]
您好：       我已收到邮件，将会尽快回复您。
