### ISSUE TITLE
gradientColorChange 与 pureColorChange  调用两次

### ISSUE THREAD

**Issue by zhuanglinxin** [aesoper101/vue3-colorpicker#36]
打开色板在纯色与渐变色分别选取颜色后     gradientColorChange 与 pureColorChange  都会调用两次
![image](https://user-images.githubusercontent.com/49221520/210741249-c550a991-37d0-4a56-aa19-d098a1f89cb0.png)

**Comment by zhuanglinxin** [comment]
![image](https://user-images.githubusercontent.com/49221520/210742464-dc884d52-8286-4484-a321-accc80ad9f2a.png)

**Comment by alonehover** [comment]
fixed by v2.1.2
