### ISSUE TITLE
v-model value is not updated while moving cursor, only on mouse up

### ISSUE THREAD

**Issue by steffanhalv** [aesoper101/vue3-colorpicker#39]
Value should be updated while dragging the cursor, not only on mouseup event

**Comment by alonehover** [comment]
I achieve this effect by providing the `debounce` attribute in 2.1.3, with a default value of 100(ms). If needed, you can set it to 0.

**Comment by titusdecali** [comment]
@alonehover I don't see that changing Debounce (for current version or 2.1.3) actually does what @steffanhalv was trying to achieve. Can you confirm you see the color changing when holding mousedown and dragging? (in my opinion, this should be the default behavior).
Also, thanks for the great library!

**Comment by alonehover** [comment]
@titusdecali What are the other part of the color spectrum ? can you describe it in detail ？

**Comment by steffanhalv** [comment]
> @titusdecali What are the other part of the color spectrum ? can you describe it in detail ？

If you click on any color in the spectrum, but not touching the selector (circle for the selected color), the selected color should change to where you clicked and the selector / circle should jump to where you clicked and still be dragganle as long as you hold the mouse or touch event.

@titusdecali Is correct, that is what I meant.
Because of this problem I have been stuck with version 1.0.8 for a long time, as this works like this.

**Comment by alonehover** [comment]
`2.3.0` has been published, i think the issue was fixed, please try it.
