### ISSUE TITLE
can't show on mouse click

### ISSUE THREAD

**Issue by Tini79** [aesoper101/vue3-colorpicker#40]
when I click on the component for the first time it doesn't show unless I scroll up/down on my laptop screen then the widget will show up as how it expected. It looks like it got delayed tho. Why does it happen?

**Comment by wellington-tinho** [comment]
I'm having the same problem, someone have already found a solution to this. I'd be grateful.

**Comment by wellington-tinho** [comment]
I'm having the same problem, someone have already found a solution to this? 
I'd be grateful.

**Comment by alonehover** [comment]
Version 2.1.3 is updated. I have change popperjs options, maybe it is fixed

**Comment by Tini79** [comment]
@wellington-tinho @alonehover Ohh thank you for your solutions guys. But, in the meantime, I've tried to add window scrollTo when I click on the button that trigger this widget to show up. Thus the widget will be shown after I click on the button. Maybe l'll try some of your solutions to see which one works best later on.
