### ISSUE TITLE
Error: component is missing template or render function.

### ISSUE THREAD

**Issue by prpanto** [aesoper101/vue3-colorpicker#41]
I have this error: component is missing template or render function. I try to use as simple as is it.
My usage:
```html
<template>
  <ColorPicker v-model:pureColor="pureColor" />
</template>

<script setup>
import { ref } from 'vue'
import ColorPicker from "vue3-colorpicker"
import "vue3-colorpicker/style.css"

const pureColor = ref('red')
</script>
```

**Comment by gigabites19** [comment]
Since author did not bother to leave resolution before closing the issue, this is for anyone who comes here looking for a solution: you need to wrap `ColorPicker` component in a `div` tag (have not tested with other tags), e.g.:
```
<template>
    <div>
        <ColorPicker />
    </div>
</template>
```
