### ISSUE TITLE
Problem with selector positioning

### ISSUE THREAD

**Issue by zhutongtian** [aesoper101/vue3-colorpicker#42]
![image](https://user-images.githubusercontent.com/33335983/223887385-4fb60359-4e91-4882-b54a-2b394067ec6c.png)
There is a problem with selector positioning. How can I solve it

**Comment by AckermanFernando** [comment]
Tive o mesmo problema, percebi que ao rolar a seção o seletor atualiza sua posição para o lugar certo. O que eu fiz foi adicionar um evento para rolar a seção alguns pixels para baixo quando for efetuado o click para abrir o seletor.

**Comment by zhuanglinxin** [comment]
I have the same problem，How to solve it?

**Comment by alonehover** [comment]
Version 2.1.3 is updated. I have change popperjs options, maybe it is fixed

**Comment by yiyi-an** [comment]
> Version 2.1.3 is updated. I have change popperjs options, maybe it is fixed

I had the same problem and it was fixed after upgrading to 2.1.3，THANKS!  (·:
