### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by webxue** [aesoper101/vue3-colorpicker#45]
在setup语法糖中引入组件
`import ColorPicker from "vue3-colorpicker";
import "vue3-colorpicker/style.css";`

在template中使用
`<color-picker lang="ZH-cn" v-model:gradientColor="backgroundImage" useType="gradient" />
`
开发环境没问题
生产环境打包报错

![image](https://user-images.githubusercontent.com/48822306/232265476-787886d8-a1ba-498a-b638-76541b297fb8.png)

**Comment by alonehover** [comment]
谢谢你的反馈，需要提供一下相关的打包环境、版本，或者提供一个在线可复现的示例，方便我排查问题，也欢迎提PR~

**Comment by alonehover** [comment]
same issue #26
