### ISSUE TITLE
为什么传入新的 props.pureColor 你要触发 change 事件？不应该是主动选择颜色操作才触发吗？参考饿了么的颜色选择器组件！

### ISSUE THREAD

**Issue by blueju** [aesoper101/vue3-colorpicker#47]
为什么传入新的 props.pureColor 你要触发 change 事件？

不应该是主动选择颜色操作才触发吗？

参考饿了么的颜色选择器组件！

**Comment by blueju** [comment]
@alonehover @aesoper101

**Comment by alonehover** [comment]
您好：       我已收到邮件，将会尽快回复您。

**Comment by blueju** [comment]
使用过程中遇到一需求，如：
有一段文本，当拖动鼠标选中一段文本A时，颜色选择器应该显示文本颜色A-color，当拖动鼠标选中一段文本B时，应该显示文本颜色B-color。当颜色选择器选中颜色后，会改变这整段文本的颜色。

问题就在这：
我全选文本A，我只是想显示文本A的颜色，结果因为传入颜色组件的pureColor发生改变，结果导致整段文本的颜色都被修改成了文本A的颜色。

原因：
vue3-colorpicker 内部监听了传入的 props.pureColor，当发生改成时会 emit 触发 update:modelValue 和 change，我的个人理解当传入的颜色发生更新变化时，不应该触发改变事件，参考饿了么颜色选择器组件。

**Comment by blueju** [comment]
一开始对其进行封装，当所需颜色与颜色选择器内的颜色不同时才emit触发颜色改变事件pureColorChange，但是后面发现这种方法无法满足一些情况，改为使用时间差方式更好一些。

以下是根据自己的使用场景复现的 bug demo 和修复 bug 后的 demo。

bug demo：
https://codesandbox.io/p/sandbox/vue3-colorpickerde-bug-37ozqb

修复 bug 后的 demo：
https://codesandbox.io/p/sandbox/vue3-colorpickerde-bug-forked-i7pzlf
