### ISSUE TITLE
<bug>vue3+vite打包到线上环境以后 ，不显示组件-线上无任何错误提示

### ISSUE THREAD

**Issue by notlaughingzzm** [aesoper101/vue3-colorpicker#6]
但是可以明确知道颜色组件出问题了
因为颜色组件以下的内容全部不显示了
功能失效

**Comment by aesoper101** [comment]
@notlaughingzzm 你好，这个问题能提供案例demo么，方便修复。还有已经更新了v2新版本，欢迎指正。
