### ISSUE TITLE
奇怪，但色调滑块是相反的。(Strange but hue slider is reverse)

### ISSUE THREAD

**Issue by dijitalbrains-dev** [aesoper101/vue3-colorpicker#60]
![image](https://github.com/aesoper101/vue3-colorpicker/assets/93189481/eda79bf1-3c41-4002-abce-e324f30724e7)

![image](https://github.com/aesoper101/vue3-colorpicker/assets/93189481/57980c24-8a99-4116-b378-ada9f0c7eaff)

**Comment by alonehover** [comment]
Is it the latest version(2.1.6)?

**Comment by dijitalbrains-dev** [comment]
My version is 2.1.4. I reviewed your code and identified an issue in Hue.vue; there's a problem with the CSS gradient direction.

**Comment by dijitalbrains-dev** [comment]
Thanks, I just updated the package and it's ok now.
