### ISSUE TITLE
[BUG]isWidget默认为选色模式，无法关闭？

### ISSUE THREAD

**Issue by srarlight** [aesoper101/vue3-colorpicker#64]
![image](https://github.com/aesoper101/vue3-colorpicker/assets/46178001/20ae3938-40a3-412b-98bb-39e5e9cef61d)
想在编辑的时候默认展开  是否有提供属性控制展开关闭状态？

**Comment by alonehover** [comment]
you can use a boolean value control it
```
<color-picker :is-widget="false"/>
```
