### ISSUE TITLE
[BUG] ‘vue3-colorpicker/dist/style.css’ 文件消失

### ISSUE THREAD

**Issue by wengdongyang** [aesoper101/vue3-colorpicker#65]
**Describe the bug**
版本：2.2.0。发现‘vue3-colorpicker/dist/style.css’文件消失

**Comment by alonehover** [comment]
sorry, it is my mistake, include error folder and files in publish content. I had publish new version 2.2.1, pls upgrade to fix it.

**Comment by wengdongyang** [comment]
I tried. But the latest version is 2.2.0. please publish again.

**Comment by alonehover** [comment]
the latest version is 2.2.2 now in npm, pls check again : )
