### ISSUE TITLE
we don't f*word know chinese

### ISSUE THREAD

**Issue by eraygundogmus** [aesoper101/vue3-colorpicker#7]

**Comment by aesoper101** [comment]
@eraygundogmus  You can use it like this

`<color-picker v-model:pureColor="pureColor" v-model:gradientColor="gradientColor" lang="En"/>`

**Comment by eraygundogmus** [comment]
@aesoper101 I just meant commit messages and docs. I could open a PR to contribute but I demoralized. Thanks anyway
