### ISSUE TITLE
[BUG] Shows console warning for picker-container prop

### ISSUE THREAD

**Issue by jagadish-evooq** [aesoper101/vue3-colorpicker#72]
**Describe the bug**
A console warning is thrown when you pass a HTML dom object as value for `pickerContainer` instead of string.

```typescript
[Vue warn]: Invalid prop: type check failed for prop "pickerContainer". Expected String with value "[object HTMLDivElement]", got HTMLDivElement  
  at <ColorPicker picker-container= <div id=​"app" data-v-app>​…​</div>​ > 
  at <App>
```

**To Reproduce**

1. Use the below code snippet which uses the mentioned prop

```typescript
<template>
  <color-picker :picker-container="pickerContainer" />
</template>

<script>
import { ColorPicker } from "vue3-colorpicker";
import "vue3-colorpicker/style.css";

export default {
  name: 'App',
  components: {
    'color-picker': ColorPicker
  },
  data() {
    return {
      pickerContainer: document.querySelector("#app"),
    };
  },
}
</script>
```

**Expected behavior**
Shouldn't display warning as HTML element is an accepted data type of `pickerContainer` prop.

**Screenshots**
<img width="1665" alt="Screenshot 2023-10-25 at 5 08 34 PM" src="https://github.com/aesoper101/vue3-colorpicker/assets/99231404/1afa8d36-a0bf-48c8-991e-9c6fd40f42c2">

**Comment by haixin-fang** [comment]
https://github.com/haixin-fang/colorpickers

@jagadish-evooq  The issue has been fixed
