### ISSUE TITLE
vue3-color-picker在线上环境中显示空白问题

### ISSUE THREAD

**Issue by Sober-D** [aesoper101/vue3-colorpicker#74]
在本地环境和测试环境中没问题，在线上环境中组件会不显示，在class名为 .vc-colorpicker--container的 div中元素都消失了，显示空白
版本为2.2.2，在2.1.5版本中也不能
![image](https://github.com/aesoper101/vue3-colorpicker/assets/64947799/51c3f35c-4cca-4243-988f-d405c6a97ea2)

<color-picker
        v-model:pureColor="data.Color"
        format="hex"
        @update:pureColor="handleColor"
        is-widget
      />
     这是使用时设置的属性
     import { ColorPicker } from 'vue3-colorpicker'
  import 'vue3-colorpicker/style.css'
     这是引入的内容

**Comment by alonehover** [comment]
目前我没法复现该问题，能否描述清楚你的编译部署环境信息，或者提供可复现demo，谢谢
