### ISSUE TITLE
[BUG] Color picker auto completes 3 letter hex code to 6 letter hex code

### ISSUE THREAD

**Issue by gethios** [aesoper101/vue3-colorpicker#76]
**Describe the bug**
When typing in `#123` in the input field it expands the hex code to `#112233` but I expect it to stay `#123` and just change the color. The expansion causes issues when typing in hex codes manually. Example if I want to type in `0f6cbd`, when I typed `0f6` it expands to `00ff66` which is not what I expect.

**To Reproduce**
1. Type any 3 letter hex code into the input box
2. The hex code expands from 3 letters to 6 letters

**Expected behavior**
I expect the expansion not to happen. Just change color if the 3 letter hex code is a valid color.

**Comment by tienthanh2509** [comment]
Same for me, it auto-completes the hex code, doesn't let the user input the rest things
