### ISSUE TITLE
希望支持自定义预设功能

### ISSUE THREAD

**Issue by dsd350** [aesoper101/vue3-colorpicker#79]
![Snipaste_2023-12-20_10-20-03](https://github.com/aesoper101/vue3-colorpicker/assets/66772170/5a7137bc-068c-4930-bdb8-342dbfd34ed0)

**Comment by alonehover** [comment]
暂时没有该计划，可以考虑使用`2.3.0`的slot来自定义插槽实现预设颜色的功能.
