### ISSUE TITLE
npm安装的似乎不是最新版本，没有zIndex相关配置

### ISSUE THREAD

**Issue by zxdstyle** [aesoper101/vue3-colorpicker#8]

**Comment by zxdstyle** [comment]
@aesoper101

**Comment by aesoper101** [comment]
@zxdstyle 2.0.4是最新的版本，zIndex只对以下两种情况有作用

1. 当isWidget为true的时候zIndex对当前显示的组件起作用
2. 当isWidget为false时zIndex对弹出的吸色盘起作用。

当前isWidget为false时如果想要对非弹出层起作用的话可以自己添加style.

如果还不能解决的话，麻烦在codesandbox建一个问题demo,方便解决，谢谢

**Comment by zxdstyle** [comment]
![image](https://user-images.githubusercontent.com/38398954/143553396-056a7f02-60cf-470c-ad8d-875aa99c91f2.png)
没有 2.0.4

**Comment by aesoper101** [comment]
@zxdstyle 这可能是你本地缓存的原因了，把`yarn.lock`删除 或者把`node_modules`删除重新安装试试，实在不行`yarn cache clean` 删除掉所有本地包缓存,我试了下下载2.0.4是没问题的
![image](https://user-images.githubusercontent.com/6196769/143555135-41cb0330-ce3e-4bd2-a42c-217be954eac4.png)

**Comment by zxdstyle** [comment]
好奇怪，你说的办法我都试了，还是不行
![image](https://user-images.githubusercontent.com/38398954/143556092-08398102-f134-4b2a-9961-e7124650cc62.png)

**Comment by aesoper101** [comment]
用淘宝源么？如果是的话用官方源试试。我之前装其他的依赖也遇到这个问题

**Comment by zxdstyle** [comment]
应该就是淘宝镜像的问题，官方好的，麻烦了

**Comment by aesoper101** [comment]
客气了
