### ISSUE TITLE
希望支持颜色重置功能，重置为一开始的默认颜色

### ISSUE THREAD

**Issue by CodingAndSleeping** [aesoper101/vue3-colorpicker#80]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SKT1yang** [comment]
The reset function is very important and is not available in other similar components.

**Comment by alonehover** [comment]
Thk for your suggestion, i had add a slot named `extra` in `2.3.0`, support add custom operate.   [online example](https://aesoper101.github.io/vue3-colorpicker/?path=/story/example-colorpicker--extra-slot)
version `2.3.0` has been published, you can try it.

**Comment by blairjanis** [comment]
I'm trying to execute the extra slot in 2.3.0 but am not able to get it to work and the online example doesn't show the code.  I'm quite certain this is a disconnect in my understanding of how named slots work but 30 minutes of googling and ai did not get me what I need.

UPDATE:  Must be a long day.  I got it to work.  If anyone else is looking for a working example, here is my code:

```
<color-picker v-model:pureColor="pureColor" round-history shape="circle">
    <template v-slot:extra>
        <div class='btn-reset' @click="pureColor='#5d35b0'">Reset</div>
    </template>
</color-picker>```
