### ISSUE TITLE
 SyntaxError: The requested module 'gradient-parser' does not provide an export named 'parse'

### ISSUE THREAD

**Issue by sol-21** [aesoper101/vue3-colorpicker#96]
I encountered a SyntaxError when trying to use the vue3-colorpicker component in my Vue 3 project. The error indicates that the gradient-parser module does not provide a named export called parse.
main.js:16 SyntaxError: The requested module '/node_modules/gradient-parser/build/node.js' does not provide an export named 'parse' (at index.es.js:7:27)

**Comment by Fei-xiangShi** [comment]
Hello, I've encountered the same issue, how did you fix it eventually? Thank you for your reply!

**Comment by sol-21** [comment]
> Hello, I've encountered the same issue, how did you fix it eventually? Thank you for your reply!

Hello! I faced a SyntaxError using the vue3-colorpicker component, indicating that gradient-parser did not export parse. To fix this, I updated my Vite configuration's optimizeDeps section
you can completely remove the optimizeDeps section from your Vite configuration and see if the project runs fine without any issues:
or Including gradient-parser resolved the issue.
```
optimizeDeps: {
    include: ['gradient-parser'],
    noDiscovery: true
},
```
If everything works without it, you can keep your configuration clean and avoid unnecessary dependencies. Hope this helps!

**Comment by sol-21** [comment]
l

**Comment by justgigio** [comment]
For those who are facing this issue using Nuxt3, here is what worked to me (thx @sol-21 !):

`nuxt.config.ts`
````
  vite: {
    optimizeDeps: {
      include: ['gradient-parser']
    }
  },
````
